import { google } from 'googleapis';

export interface NodeAction {
  type: 'google_calendar';
  calendarId: string;
  titleTemplate: string;
  durationMinutes?: number;
}

export class ActionRunnerService {
  /**
   * Executes configured actions natively inside the backend.
   * Pulls dynamic variables from the extractedData object to populate titles and times.
   */
  async executeAction(
    action: NodeAction,
    extractedData: any,
    userName: string | null,
  ): Promise<boolean> {
    console.log(`[ActionRunner] Executing action of type '${action.type}'...`);

    if (action.type === 'google_calendar') {
      return this.executeGoogleCalendarAction(action, extractedData, userName);
    }

    console.warn(`[ActionRunner] Unknown action type: ${action.type}`);
    return false;
  }

  /**
   * Flexibly finds a field value from extracted data by checking multiple possible field names.
   */
  private findField(data: any, ...candidates: string[]): string | undefined {
    for (const key of candidates) {
      if (data[key]) return String(data[key]);
    }
    // Also try case-insensitive matching against all keys
    const dataKeys = Object.keys(data);
    for (const candidate of candidates) {
      const match = dataKeys.find(k => k.toLowerCase() === candidate.toLowerCase());
      if (match && data[match]) return String(data[match]);
    }
    return undefined;
  }

  private async executeGoogleCalendarAction(
    action: NodeAction,
    data: any,
    userName: string | null,
  ): Promise<boolean> {
    if (!action.calendarId) {
      console.warn('[ActionRunner] Google Calendar action requires a `calendarId` config block.');
      return false;
    }
    
    // Flexibly find date/time fields — Validator nodes may use different field names
    const dateValue = this.findField(data, 'date', 'preferredDate', 'fecha', 'appointmentDate');
    const timeValue = this.findField(data, 'time', 'preferredTime', 'hora', 'appointmentTime');

    // Allow combined date+time in a single field (e.g. "2026-03-02 15:00")
    const combinedDateTime = dateValue && !timeValue && /\d{4}-\d{2}-\d{2}.*\d{1,2}:\d{2}/.test(dateValue);

    if (!dateValue) {
      console.log('[ActionRunner] Missing date in extracted data. Available keys:', Object.keys(data));
      return false;
    }

    console.log(`[ActionRunner] Found date="${dateValue}", time="${timeValue || '(combined)'}"`);

    try {
      // 1. Authenticate with Google Cloud
      const auth = new google.auth.GoogleAuth({
        keyFile: './atom-credentials.json',
        scopes: ['https://www.googleapis.com/auth/calendar.events'],
      });
      const calendar = google.calendar({ version: 'v3', auth });

      // 2. Parse Date/Time
      let startTime: Date;
      if (combinedDateTime) {
        startTime = new Date(dateValue);
      } else if (timeValue) {
        startTime = new Date(`${dateValue} ${timeValue}`);
      } else {
        // Date only — default to 3:00 PM (common business hours)
        startTime = new Date(`${dateValue} 15:00`);
      }

      if (isNaN(startTime.getTime())) {
          console.error('[ActionRunner] Invalid date format generated by LLM:', dateValue, timeValue);
          return false;
      }
      
      const duration = action.durationMinutes || 60;
      const endTime = new Date(startTime.getTime() + duration * 60 * 1000);

      // 3. Resolve Template Variables
      let title = action.titleTemplate || `Meeting with ${userName || 'Customer'}`;
      title = title.replace('{{name}}', userName || 'Customer');
      Object.keys(data).forEach((key) => {
        title = title.replace(new RegExp(`{{\\s*${key}\\s*}}`, 'g'), data[key] || '');
      });

      // 4. Fire the Request!
      console.log(`[ActionRunner] Creating event on ${action.calendarId}: "${title}" at ${startTime.toISOString()}`);

      await calendar.events.insert({
        calendarId: action.calendarId,
        requestBody: {
          summary: title,
          description: `Automatically created by Atom Auto Agent.\n\nExtracted Parameters:\n${JSON.stringify(data, null, 2)}`,
          start: { dateTime: startTime.toISOString() },
          end: { dateTime: endTime.toISOString() },
        },
      });

      console.log('[ActionRunner] ✅ Calendar event successfully created!');
      return true;
    } catch (error: any) {
       console.error('[ActionRunner] ❌ Google Calendar API failed:', error.message || error);
       return false;
    }
  }
}
