import { google } from 'googleapis';

export interface NodeAction {
  type: 'google_calendar';
  calendarId: string;
  titleTemplate: string;
  durationMinutes?: number;
}

export class ActionRunnerService {
  /**
   * Executes configured actions natively inside the backend.
   * Pulls dynamic variables from the extractedData object to populate titles and times.
   */
  async executeAction(
    action: NodeAction,
    extractedData: any,
    userName: string | null,
  ): Promise<boolean> {
    console.log(`[ActionRunner] Executing action of type '${action.type}'...`);

    if (action.type === 'google_calendar') {
      return this.executeGoogleCalendarAction(action, extractedData, userName);
    }

    console.warn(`[ActionRunner] Unknown action type: ${action.type}`);
    return false;
  }

  private async executeGoogleCalendarAction(
    action: NodeAction,
    data: any,
    userName: string | null,
  ): Promise<boolean> {
    if (!action.calendarId) {
      console.warn('[ActionRunner] Google Calendar action requires a `calendarId` config block.');
      return false;
    }
    
    // We need at LEAST a date and time to put something on a calendar
    if (!data.date || !data.time) {
      console.log('[ActionRunner] Missing date/time in extracted data. Skipping calendar creation.');
      return false;
    }

    try {
      // 1. Authenticate with Google Cloud
      // Notice: If 'atom-credentials.json' doesn't exist, this will naturally fail, which is exactly
      // what we expect until the Dealership provides their API key.
      const auth = new google.auth.GoogleAuth({
        keyFile: './atom-credentials.json',
        scopes: ['https://www.googleapis.com/auth/calendar.events'],
      });
      const calendar = google.calendar({ version: 'v3', auth });

      // 2. Parse Date/Time
      // E.g. data.date = "2026-03-05", data.time = "10:00 AM"
      const startTimeStr = `${data.date} ${data.time}`;
      const startTime = new Date(startTimeStr);
      if (isNaN(startTime.getTime())) {
          console.error('[ActionRunner] Invalid date format generated by LLM:', startTimeStr);
          return false;
      }
      
      const duration = action.durationMinutes || 60;
      const endTime = new Date(startTime.getTime() + duration * 60 * 1000);

      // 3. Resolve Template Variables
      // User says: "Appointment for {{name}} (Interested in: {{vehicleInterest}})"
      let title = action.titleTemplate || `Meeting with ${userName || 'Customer'}`;
      title = title.replace('{{name}}', userName || 'Customer');
      Object.keys(data).forEach((key) => {
        title = title.replace(new RegExp(`{{\\s*${key}\\s*}}`, 'g'), data[key] || '');
      });

      // 4. Fire the Request!
      console.log(`[ActionRunner] Creating event on ${action.calendarId}: "${title}" at ${startTime.toISOString()}`);

      await calendar.events.insert({
        calendarId: action.calendarId,
        requestBody: {
          summary: title,
          description: `Automatically created by Atom Auto Agent.\n\nExtracted Parameters:\n${JSON.stringify(data, null, 2)}`,
          start: { dateTime: startTime.toISOString() },
          end: { dateTime: endTime.toISOString() },
        },
      });

      console.log('[ActionRunner] ✅ Calendar event successfully created!');
      return true;
    } catch (error: any) {
       console.error('[ActionRunner] ❌ Google Calendar API failed:', error.message || error);
       // We intentionally soft-fail here so the LLM pipeline still responds to the user!
       return false;
    }
  }
}
